---
- hosts: '{{myhosts}}' 
  remote_user: '{{admin_user}}'
  gather_facts: false
  tasks:
  - name: echo
    shell: echo 'okokokok'
    become: true
    
  - name: echo file
    shell: echo '1231' > /tmp/aa
    become: true
